//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.SyntaxColoringService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETokenType", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    public enum ETokenType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_KEYWORD = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_ID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_NUMBER = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_STRING = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_ROUND_BRACKET = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_CURLY_BRACKET = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_SQUARE_BRACKET = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_SEMICOLON = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_UNARY_FRONT_OPERATOR = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_UNARY_BACK_OPERATOR = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_BINARY_OPERATOR = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_COMMENT = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_ERROR = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_EMPTY = 13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyntaxColoringService.ISyntaxColoringService")]
    public interface ISyntaxColoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyntaxColoringService/GetTokensColorData", ReplyAction="http://tempuri.org/ISyntaxColoringService/GetTokensColorDataResponse")]
        string GetTokensColorData(System.Collections.Generic.KeyValuePair<string, Editor.SyntaxColoringService.ETokenType>[] tokenList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyntaxColoringService/GetTokensColorData", ReplyAction="http://tempuri.org/ISyntaxColoringService/GetTokensColorDataResponse")]
        System.Threading.Tasks.Task<string> GetTokensColorDataAsync(System.Collections.Generic.KeyValuePair<string, Editor.SyntaxColoringService.ETokenType>[] tokenList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyntaxColoringServiceChannel : Editor.SyntaxColoringService.ISyntaxColoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyntaxColoringServiceClient : System.ServiceModel.ClientBase<Editor.SyntaxColoringService.ISyntaxColoringService>, Editor.SyntaxColoringService.ISyntaxColoringService {
        
        public SyntaxColoringServiceClient() {
        }
        
        public SyntaxColoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyntaxColoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyntaxColoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyntaxColoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTokensColorData(System.Collections.Generic.KeyValuePair<string, Editor.SyntaxColoringService.ETokenType>[] tokenList) {
            return base.Channel.GetTokensColorData(tokenList);
        }
        
        public System.Threading.Tasks.Task<string> GetTokensColorDataAsync(System.Collections.Generic.KeyValuePair<string, Editor.SyntaxColoringService.ETokenType>[] tokenList) {
            return base.Channel.GetTokensColorDataAsync(tokenList);
        }
    }
}
